	.INCLUDE "HEADERS.ASM"
	.INCLUDE "RAM.ASM"
	.INCLUDE "GLOBALS.ASM"	
	.INCLUDE "ENGINE.ASM"
		
	.BANK PRG_BANKTABLE_0X1		
	.ORG BANK_PRIMARY_START	
		PALETTES_PEOPLE: .INCBIN "ASSETS/PALETTES/PEOPLE.DAT"	
		PALETTES_MANSION: .INCBIN "ASSETS/PALETTES/MANSION.DAT"	
		BACKGROUND_MANSION: .INCBIN "ASSETS/BACKGROUNDS/MANSION.BIN"	
	
		
		ROM_START:
			SEI          
			CLD          
			LDX #$40
			STX $4017    
			LDX #$FF
			TXS          
			INX          
			STX $2000    
			STX $2001    
			STX $4010  
			LDA #$00
			STA $B003
			
		VBLANKWAIT

		CLEAR_MEMORY:
			LDA #$00
			STA $0000, X    
			STA $0100, X	
			STA $0300, X
			STA $0400, X
			STA $0500, X
			STA $0600, X
			STA $0700, X
			LDA #$FF
			STA $0200, X	
			INX
			BNE CLEAR_MEMORY
			
			
			LDA #BANK(MUSIC_FLOOR1_SAMPLES)
			STA VRC6_C000_PRG_SELECT_ADDR		
			


		LDA #(GRAPHICS_PEOPLE/$400)
		STA VRC6_CHRSELECT_PATTERN1X1   
		LDA #(GRAPHICS_PEOPLE/$400)+$01
		STA VRC6_CHRSELECT_PATTERN1X2   
		LDA #(GRAPHICS_PEOPLE/$400)+$02
		STA VRC6_CHRSELECT_PATTERN1X3   
		LDA #(GRAPHICS_PEOPLE/$400)+$03
		STA VRC6_CHRSELECT_PATTERN1X4
		
		LDA #(GRAPHICS_MANSION/$400)
		STA VRC6_CHRSELECT_PATTERN2X1   
		LDA #(GRAPHICS_MANSION/$400)+$01
		STA VRC6_CHRSELECT_PATTERN2X2   
		LDA #(GRAPHICS_MANSION/$400)+$02
		STA VRC6_CHRSELECT_PATTERN2X3   
		LDA #(GRAPHICS_MANSION/$400)+$03
		STA VRC6_CHRSELECT_PATTERN2X4
				
		LDA #COMBAT_RANK_S
		STA COMBAT_RANK		
		LDA COMBAT_RANK
		STA AUDIO_CHANNEL_STATUS
		
		LOAD_PALETTES PALETTES_MANSION, #LP_ARG_DEST_PALLETE_TABLE_0
		LOAD_PALETTES PALETTES_PEOPLE, #LP_ARG_DEST_PALLETE_TABLE_1
		LOAD_BACKGROUND BACKGROUND_MANSION, #NAMETABLE_1

		SET_PLAYER_POSITION #$80, #$C0
		SET_FRAME #ERICK_IDLE_DOWN, #ERICK_IDLE_DOWN_END
		SPAWN_SPRITE ERICK_IDLE_DOWN, #$00
		UPDATE_SPRITE_POSITION		
		
	
		
		ENABLE_NMI
		
		JMP VRC6_BANK_SWITCH_ROUTINE


	.BANK PRG_BANKTABLE_0X2
	.ORG BANK_SECONDARY_START
		
	.BANK PRG_BANKTABLE_1X1
	.ORG BANK_PRIMARY_START
		FUCK:
			START_MUSIC MUSIC_FLOOR1
			JMP GAME_LOOP
			
	.BANK PRG_BANKTABLE_1X2
	.ORG BANK_SECONDARY_START	
		MUSIC_FLOOR1: .INCLUDE "botanik2extended.asm"	
		
	.BANK PRG_BANKTABLE_2X1
	.ORG BANK_PRIMARY_START

	

		
	.BANK PRG_BANKTABLE_2X2
	.ORG BANK_SECONDARY_START

			
	.BANK PRG_BANKTABLE_0X3
	.ORG BANK_DPCM_SAMPLES_START
		MUSIC_FLOOR1_SAMPLES: ;.INCBIN "yeahcool.dmc"
		
	.BANK PRG_BANKTABLE_0X4
	.ORG BANK_FIXED_START
	.ORG FAMISTUDIO_NESASM_CODE_ORG
		.INCLUDE "FAMISTUDIO_NESASM.ASM"	
		.INCLUDE "FRAMEDATA.ASM"	
		
		NMI:		
			OAMDMA_TRANSFER	           
			UPDATE_SPRITE_POSITION
			ANIMATE_SPRITES
			UPDATE_SCROLL
			LATCH_CONTROLLER_P1
			READ_CONTROLS_P1		
		
			JSR famistudio_update
			
			LDA #(PPUCTRL_GENERATE_NMI_ON_VB + PPUCTRL_BACKGROUND_PT_ADDRESS_1)
			STA PPU_REGISTER_PPUCTRL
			
			LDA #(PPUMASK_SHOW_SPRITES + PPUMASK_SHOW_BACKGROUND + PPUMASK_SHOW_BACKGROUND_LEFT + PPUMASK_SHOW_SPRITES_LEFT)
			STA PPU_REGISTER_PPUMASK

			INC ANIMATION_DELAY
			LDA ANIMATION_DELAY
			AND #%111
			BEQ DOIT
			RTI
		DOIT:
			LDA #(ERICK_IDLE_DOWN_END-ERICK_IDLE_DOWN)-$10
						
			LSR A
			LSR A
			LSR A
			LSR A
			CMP PLAYER_FRAME

			BEQ RESET
			INC PLAYER_FRAME
			RTI
		RESET:
			LDA #$00
			STA PLAYER_FRAME


		RTI
	
		
	;.ORG BANK_SWITCH_ROUTE_LOC
		VRC6_BANK_SWITCH_ROUTINE:
			VRC6_BANK_SWITCH VRC6_8000_A000_PRG_SELECT_ADDR, FUCK
			
	
	.ORG FIXED_GAME_LOOP_LOC
		GAME_LOOP:				
			JMP GAME_LOOP
		
	.ORG FIXED_VECTORS_LOC
		.DW NMI               
		.DW ROM_START       	
		.DW 0 				

	.BANK CHR_BANKTABLE
		.ORG $0000
		GRAPHICS_PEOPLE:	 .INCBIN "ASSETS/GRAPHICS/PEOPLE.CHR"
		.ORG $1000
		GRAPHICS_MANSION:	 .INCBIN "ASSETS/GRAPHICS/MANSION.CHR"
		.ORG $2000
		GRAPHICS_MOREPEOPLE: .INCBIN "ASSETS/GRAPHICS/MOREPEOPLE.CHR"
		.ORG $3000
		GRAPHICS_STRUCTURES: .INCBIN "ASSETS/GRAPHICS/STRUCTURES.CHR"
			