;this file for FamiStudio Sound Engine generated by FamiStudio

_music_data:
	.db 1
	.dw .instruments
	.dw .samples-4
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,.song0ch5,.song0ch6,.song0ch7
	.db LOW(.tempo_env_8_mid), HIGH(.tempo_env_8_mid), 0, 0

.instruments:
	.dw .env1,.env0,.env3,.env2
	.dw .env1,.env0,.env3,.env2

.samples:
	.db $00+LOW(FAMISTUDIO_DPCM_PTR),$24,$0f,$40	;1 (Sample 1)
	.db $09+LOW(FAMISTUDIO_DPCM_PTR),$25,$0f,$40	;2 (Sample 2)
	.db $13+LOW(FAMISTUDIO_DPCM_PTR),$45,$0f,$40	;3 (Sample 3)
	.db $25+LOW(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40	;4 (Sample 4)

.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $04,$cf,$7f,$00,$01
.env2:
	.db $00,$c0,$7f,$00,$01
.env3:
	.db $7f,$00,$00
.tempo_env_8_mid:
	.db $03,$05,$04,$06,$05,$80
.song0ch0:
.song0ch0loop:
	.db $6a, LOW(.tempo_env_8_mid), HIGH(.tempo_env_8_mid)
.song0ref5:
	.db $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b
	.db $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b
	.db $ff, $23
	.dw .song0ref5
	.db $6b
	.db $ff, $23
	.dw .song0ref5
	.db $6b
	.db $ff, $23
	.dw .song0ref5
	.db $fd
	.dw .song0ch0loop
.song0ch1:
.song0ch1loop:
.song0ref62:
	.db $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7
	.db $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $fd
	.dw .song0ch1loop
.song0ch2:
.song0ch2loop:
	.db $80
.song0ref111:
	.db $28, $26, $24, $22, $20, $1e, $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $00, $9d, $28, $26, $24, $22, $20, $1e
	.db $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $00, $9d
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
.song0ref153:
	.db $28, $26, $24, $22, $20, $1e, $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $00, $9d, $28, $26, $24, $22, $20, $1e
	.db $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $28, $26, $24, $22, $20, $1e, $1c, $1a, $18, $16, $14, $12, $10, $0e
	.db $0c, $0a
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
.song0ref239:
	.db $28, $26, $24, $22, $20, $1e, $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $40, $8d, $3e, $8d, $3b, $8d, $37, $8d
	.db $39, $8d, $3b, $8d, $39, $8d, $37, $8d, $36, $8d, $37, $8d, $34, $9d, $36, $8d, $37, $8d, $39, $9d, $37, $8d, $68, $ff
	.db $38, $68, $fe, $81, $68, $fd, $81, $68, $fc, $81, $68, $03, $39, $68, $02, $81, $68, $01, $81, $68, $00, $81, $68, $fe
	.db $81, $68, $fd, $83, $68, $fe, $81, $68, $00, $81, $68, $01, $81, $68, $03, $83, $68, $00, $37, $8d, $39, $8d, $3b, $8d
	.db $3c, $9d, $3b, $8d, $39, $9d, $37, $8d, $68, $ff, $3a, $68, $fe, $81, $68, $fd, $81, $68, $03, $3b, $68, $02, $81, $68
	.db $01, $81, $68, $00, $93, $37, $8d, $3b, $8d, $40, $9d, $42, $8d, $43, $9d, $42, $9b, $00, $42, $85, $43, $85, $42, $8d
	.db $40, $8d, $3e, $8d, $40, $9d, $3e, $8d, $3b, $9d, $3c, $8d, $3b, $8d, $68, $fe, $81, $68, $fd, $83, $68, $fe, $81, $68
	.db $00, $81, $68, $01, $81, $68, $03, $85, $68, $01, $81, $68, $00, $81, $68, $fe, $81, $68, $fd, $83, $68, $ff, $81, $68
	.db $00, $81, $68, $ff, $3a, $68, $fc, $39, $81, $68, $00, $3a, $68, $01, $3b, $68, $03, $3c, $68, $fe, $81, $68, $02, $3d
	.db $68, $fe, $3c, $68, $fd, $3b, $68, $02, $81, $68, $01, $3a, $68, $fc, $39, $68, $03, $3a, $68, $fe, $81, $68, $00, $3b
	.db $83
.song0ref480:
	.db $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $40, $3b, $81, $40, $3b, $81, $40, $3b, $81
	.db $40, $3b, $81, $40, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81
	.db $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b
.song0ref542:
	.db $47, $9d, $3b, $8d, $47, $8d, $48, $8d, $47, $8d, $45, $8d, $47, $8d, $3b, $95, $00, $85, $47, $8d, $48, $8d, $4a, $8d
	.db $48, $8d, $47, $8d, $43, $8d, $45, $9d, $43, $8d, $42, $8d, $68, $fe, $81, $68, $01, $43, $81, $68, $fe, $42, $68, $00
	.db $81, $68, $01, $81, $68, $fe, $41, $81, $68, $00, $40
.song0ref601:
	.db $8d, $42, $8d, $43, $8d, $42, $a1, $47, $81, $4b, $81, $42, $81, $47, $81, $4b, $81, $42, $81, $47, $81, $43, $81, $47
	.db $81, $4c, $81, $43, $81, $47, $81, $4c, $81, $43, $81, $47, $81, $43, $81, $47, $81, $4e, $81, $43, $81, $47, $81, $4e
	.db $81, $43, $81, $47, $81, $4f, $8d, $68, $ff, $4d, $4c, $4b, $68, $00, $4a, $49, $68, $ff, $48, $47, $68, $fe, $46, $68
	.db $00, $4c, $8d, $4e, $8d, $4f, $8d, $4e, $8d, $4c, $8d, $4a, $8d, $4c, $8f, $68, $ff, $83, $68, $00, $85, $68, $01, $83
	.db $68, $00, $4f, $8d, $53, $95, $00, $95, $54, $8d, $51, $ad, $4f, $9d, $4e, $8d, $68, $01, $4d, $4c, $68, $ff, $4a, $49
	.db $68, $fe, $48, $68, $01, $81, $47, $68, $00, $46, $4e, $8d, $4f, $8d, $4c, $9f, $68, $ff, $83, $68, $00, $85, $68, $01
	.db $85, $68, $00, $83, $68, $ff, $85, $68, $00, $85, $68, $01, $83, $68, $00, $85, $68, $ff, $83, $68, $00, $4d, $68, $ff
	.db $4c, $68, $00, $81, $68, $ff, $4b, $68, $00, $83, $68, $01, $4c, $68, $00, $81, $68, $01, $4d, $68, $00, $83, $68, $01
	.db $81, $68, $00, $4c, $68, $01, $81, $68, $00, $4b, $83, $68, $01, $4c, $68, $00, $81, $68, $01, $4d, $68, $00, $83, $68
	.db $ff, $4c, $68, $00, $81
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $8e
	.dw .song0ref239
	.db $81, $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $3f, $3b, $81, $40, $3b, $81, $40, $3b, $81, $40, $3b
	.db $81, $40, $3b, $81, $40, $3b, $81, $40, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b, $81, $42, $3b
	.db $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81
	.db $ff, $b6
	.dw .song0ref542
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $8e
	.dw .song0ref239
	.db $3f, $3b, $81
	.db $ff, $2d
	.dw .song0ref480
	.db $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43, $3b, $81, $43
	.db $ff, $b6
	.dw .song0ref542
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $fa
	.dw .song0ref239
	.db $ff, $89
	.dw .song0ref601
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $32
	.dw .song0ref153
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $ff, $24
	.dw .song0ref111
	.db $28, $26, $24, $22, $20, $1e, $1c, $1a, $18, $16, $14, $12, $10, $0e, $0c, $0a, $00, $9d, $28, $26, $24, $00, $b7, $fd
	.dw .song0ch2loop
.song0ch3:
.song0ch3loop:
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $fd
	.dw .song0ch3loop
.song0ch4:
.song0ch4loop:
.song0ref1062:
	.db $01, $9d, $02, $8d, $02, $8d, $03, $9d, $02, $8d, $02, $8d, $01, $8d, $02, $8d, $02, $8d, $02, $8d, $03, $9d, $02, $8d
	.db $02, $8d, $01, $85, $04, $95, $02, $8d, $02, $8d, $03, $9d, $02, $8d, $02, $8d, $01, $8d, $02, $8d, $02, $8d, $04, $8d
	.db $03, $9d, $02, $85, $02, $85, $02, $85, $02, $85
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $3a
	.dw .song0ref1062
	.db $ff, $30
	.dw .song0ref1062
	.db $00, $bd, $fd
	.dw .song0ch4loop
.song0ch5:
.song0ch5loop:
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $fd
	.dw .song0ch5loop
.song0ch6:
.song0ch6loop:
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $ff, $23
	.dw .song0ref62
	.db $fd
	.dw .song0ch6loop
.song0ch7:
.song0ch7loop:
	.db $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $76, $6c, $01, $82
.song0ref1253:
	.db $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $07, $8d, $13, $8d, $07, $8d, $13, $8d
	.db $07, $8d, $13, $8d, $07, $8d, $13, $8d, $09, $8d, $15, $8d, $09, $8d, $15, $8d, $09, $8d, $15, $8d, $09, $8d, $15, $8d
	.db $0b, $8d, $17, $8d, $0b, $8d, $17, $8d, $0b, $8d, $17, $8d, $0b, $8d, $17
.song0ref1316:
	.db $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $02, $8d, $0e, $8d, $02, $8d, $0e
	.db $8d, $02, $8d, $0e, $8d, $02, $8d, $0e, $8d, $07, $8d, $13, $8d, $07, $8d, $13, $8d, $07, $8d, $13, $8d, $07, $8d, $13
	.db $8d, $06, $8d, $12, $8d, $06, $8d, $12, $8d, $06, $8d, $12, $8d, $06, $8d, $12, $8d
	.db $ff, $30
	.dw .song0ref1253
	.db $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18
	.db $ff, $41
	.dw .song0ref1316
	.db $ff, $50
	.dw .song0ref1253
.song0ref1405:
	.db $07, $8d, $13, $8d, $07, $8d, $13, $8d, $07, $8d, $13, $8d, $07, $8d, $13, $8d, $09, $8d, $15, $8d, $09, $8d, $15, $8d
	.db $09, $8d, $15, $8d, $09, $8d, $15, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d, $04, $8d, $10, $8d
	.db $ff, $80
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1253
	.db $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18
	.db $ff, $41
	.dw .song0ref1316
	.db $ff, $50
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1405
	.db $ff, $80
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1253
	.db $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18
	.db $ff, $41
	.dw .song0ref1316
	.db $ff, $50
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1405
	.db $ff, $80
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1253
	.db $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18, $8d, $0c, $8d, $18
	.db $ff, $41
	.dw .song0ref1316
	.db $ff, $50
	.dw .song0ref1253
	.db $ff, $30
	.dw .song0ref1405
	.db $ff, $78
	.dw .song0ref1253
	.db $00, $bd, $fd
	.dw .song0ch7loop
