;this file for FamiStudio Sound Engine generated by FamiStudio

macro_music_data1:
	.db 1
	.dw .instruments
	.dw .samples-4
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,950,791

.instruments:
	.dw .env5,.env7,.env17,.env15
	.dw .env6,.env1,.env17,.env15
	.dw .env3,.env23,.env16,.env15
	.dw .env19,.env21,.env24,.env15
	.dw .env18,.env13,.env24,.env15
	.dw .env22,.env13,.env24,.env15
	.dw .env9,.env2,.env20,.env15
	.dw .env12,.env23,.env20,.env15
	.dw .env4,.env11,.env14,.env15
	.dw .env8,.env7,.env17,.env15
	.dw .env6,.env1,.env17,.env25
	.dw .env6,.env1,.env17,.env0
	.dw .env6,.env1,.env17,.env10

.samples:
.env0:
	.db $80,$ff,$00,$01
.env1:
	.db $c0,$7f,$00,$00
.env2:
	.db $bd,$c3,$c2,$c2,$c1,$07,$c0,$c1,$c0,$00,$08
.env3:
	.db $00,$c7,$c7,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$03,$c2,$c2,$c1,$c0,$00,$0f
.env4:
	.db $00,$ca,$c9,$c8,$c7,$03,$c6,$05,$c5,$c4,$c5,$c5,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c2,$c2,$c1,$02,$c0,$00,$1a
.env5:
	.db $18,$cb,$ca,$ca,$c9,$03,$c8,$c9,$c8,$c9,$c8,$c9,$c8,$c9,$c8,$c9,$c8,$c9,$c8,$c9,$c8,$c9,$00,$15,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$1f
.env6:
	.db $04,$cf,$7f,$00,$01
.env7:
	.db $cc,$cc,$c1,$c0,$00,$03
.env8:
	.db $19,$c9,$c9,$c8,$02,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$c7,$c8,$00,$16,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$20
.env9:
	.db $00,$c6,$c9,$c7,$c6,$c6,$c5,$c4,$c4,$c3,$03,$c2,$04,$c1,$c1,$c0,$00,$0f
.env10:
	.db $80,$c1,$02,$c5,$ca,$00,$04
.env11:
	.db $c1,$bc,$bd,$be,$bf,$c0,$08,$bf,$00,$07
.env12:
	.db $00,$c7,$03,$c6,$09,$c5,$09,$c4,$09,$c3,$08,$c2,$09,$c1,$09,$c0,$00,$0f
.env13:
	.db $bd,$04,$be,$07,$bf,$06,$c0,$00,$06
.env14:
	.db $c0,$c1,$03,$c0,$c1,$c0,$c1,$c0,$00,$07
.env15:
	.db $00,$c0,$7f,$00,$01
.env16:
	.db $c0,$c1,$c0,$00,$02
.env17:
	.db $7f,$00,$00
.env18:
	.db $00,$c1,$c2,$02,$c3,$c3,$c4,$02,$c5,$c5,$c6,$c6,$c7,$02,$c8,$c8,$c9,$c9,$ca,$02,$cb,$00,$14
.env19:
	.db $00,$cc,$cc,$cb,$ca,$02,$c9,$02,$c8,$02,$c7,$05,$c6,$07,$c5,$07,$c4,$08,$c3,$1c,$c2,$1d,$c1,$08,$c0,$00,$18
.env20:
	.db $c0,$c1,$c1,$c0,$00,$03
.env21:
	.db $c0,$c1,$c0,$0b,$bf,$0f,$be,$03,$bf,$bf,$bf,$00,$06
.env22:
	.db $00,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$00,$08
.env23:
	.db $c1,$be,$bf,$c0,$bf,$c0,$c1,$00,$06
.env24:
	.db $c0,$c0,$c1,$c0,$02,$c1,$00,$00
.env25:
	.db $80,$c2,$c2,$c8,$00,$03
.env26:
	.db $00,$c0,$be,$bc,$ba,$b8,$b7,$b6,$b5,$02,$b6,$b7,$b8,$ba,$bc,$be,$c0,$c2,$c4,$c6,$c8,$c9,$ca,$cb,$02,$ca,$c9,$c8,$c6,$c4,$c2,$00,$01
.song0ch0:
.song0ch0loop:
	.db $7c, $69, $02, $80
.song0ref6:
	.db $11, $7d, $81, $7f, $8b, $7b, $81, $7d, $81, $7e, $f9, $7f, $81, $11, $83, $f9, $bf, $12, $83, $f9, $7c, $12
.song0ref28:
	.db $7d, $81, $7f, $83, $7b, $81, $7d, $81, $7e, $81, $7f, $81, $7c, $81, $7d, $81, $7f, $f9, $81, $7c, $69, $02
	.db $ff, $19
	.dw .song0ref6
	.db $7c, $69, $02
	.db $ff, $19
	.dw .song0ref6
	.db $7c, $69, $02, $11
.song0ref63:
	.db $7d, $81, $7f, $8b, $7b, $81, $7d, $81, $7e, $f9, $7f, $91, $7c, $81, $7d, $81, $7f, $83, $7b, $81, $7d, $81, $7e, $81
	.db $7f, $85, $70, $6e, $07, $20, $14
.song0ref94:
	.db $81, $7c, $81, $7d, $81, $7f, $8b, $7b, $81, $7d, $81, $7e, $81, $7f, $81, $62, $14
.song0ref111:
	.db $8d, $7c, $81, $7d, $81, $7f, $83, $7b, $81, $7d, $81, $7e, $81, $7f, $87, $62, $14, $fd
	.dw .song0ch0loop
.song0ch1:
.song0ch1loop:
	.db $7c, $69, $02, $92
.song0ref136:
	.db $10, $7d, $81, $7f, $8b, $7b, $81, $7d, $81, $7e, $f9, $7f, $81, $10, $83, $f9, $71, $82, $28, $72, $2b, $73, $2f, $74
	.db $34, $28, $2b, $2f, $34, $73
.song0ref166:
	.db $28, $2b, $2f, $34, $28, $2b, $2f, $34, $72
	.db $ff, $08
	.dw .song0ref166
	.db $71
	.db $ff, $08
	.dw .song0ref166
	.db $7f, $92, $11, $83, $f9, $7c, $11
	.db $ff, $0a
	.dw .song0ref28
	.db $7c, $69, $02
	.db $ff, $0a
	.dw .song0ref136
	.db $71, $82, $2b, $72, $2f, $73, $34, $74, $37, $2b, $2f, $34, $37, $73
.song0ref212:
	.db $2b, $2f, $34, $37, $2b, $2f, $34, $37, $72
	.db $ff, $08
	.dw .song0ref212
	.db $71
	.db $ff, $08
	.dw .song0ref212
	.db $7f, $92, $11, $83, $f9, $7c, $11
	.db $ff, $0a
	.dw .song0ref28
	.db $7c, $69, $02
	.db $ff, $0a
	.dw .song0ref136
	.db $71, $82, $29, $72, $2b, $73, $2e, $74, $34, $29, $2b, $2e, $34, $73
.song0ref258:
	.db $29, $2b, $2e, $34, $29, $2b, $2e, $34, $72
	.db $ff, $08
	.dw .song0ref258
	.db $71
	.db $ff, $08
	.dw .song0ref258
	.db $7f, $92, $11, $83, $f9, $7c, $11
	.db $ff, $0a
	.dw .song0ref28
	.db $7c, $69, $02, $10
	.db $ff, $0d
	.dw .song0ref63
	.db $70, $6e, $07, $20, $13
	.db $ff, $08
	.dw .song0ref94
	.db $62, $13
	.db $ff, $08
	.dw .song0ref111
	.db $62, $13, $fd
	.dw .song0ch1loop
.song0ch2:
.song0ch2loop:
.song0ref310:
	.db $96, $3d, $82, $1c, $83, $63, LOW(.env26), HIGH(.env26), $87, $63, LOW(.env15), HIGH(.env15), $64, $98, $31, $6b, $0e
	.db $82, $1c, $00, $81, $1c, $6b, $0e, $81, $00, $89, $96, $3d, $00, $83, $98, $31, $00, $8b, $96, $3d, $00, $8b, $98, $31
	.db $00, $8b, $82, $1d, $6b, $0e, $81, $00, $81, $96, $3d, $82, $1d, $83, $98, $31, $82, $1d, $6b, $0e, $81, $00, $87
	.db $ff, $24
	.dw .song0ref310
	.db $ff, $24
	.dw .song0ref310
	.db $96, $3d, $82, $1c, $83, $63, LOW(.env26), HIGH(.env26), $87, $63, LOW(.env15), HIGH(.env15), $64, $98, $31, $6b, $0e
	.db $82, $1c, $00, $85, $6b, $03, $94, $36, $00, $36
.song0ref407:
	.db $00, $83, $96, $3d, $00, $83, $98, $31, $00, $83, $96, $3d, $00, $83, $3d, $00, $8b, $98, $31, $00, $87, $6b, $04, $96
	.db $3d, $00, $98, $31
	.db $ff, $0b
	.dw .song0ref407
	.db $fd
	.dw .song0ch2loop
.song0ch3:
.song0ch3loop:
.song0ref442:
	.db $7f, $8c, $20, $85, $84, $2d, $81, $75
.song0ref450:
	.db $2d, $81, $7f, $90, $29, $85, $84, $2d, $81, $7a, $2d, $81, $7f, $2d, $81, $7a, $2d, $81, $7f, $8c, $20, $81, $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84
	.db $ff, $08
	.dw .song0ref450
	.db $ff, $12
	.dw .song0ref442
	.db $75, $84, $2d, $81, $7f, $90, $29, $85, $8c, $20, $81, $7a, $84, $2d, $7c, $8a, $29, $86, $29, $89, $7a, $84, $2d, $81
	.db $7f, $90, $29, $85, $7a, $8e, $2d, $81, $7f, $8c, $20, $81, $90, $29, $81, $29, $81, $8c, $20, $81, $84, $2d, $81, $90
	.db $29, $85, $8c, $20, $88, $2a, $83, $fd
	.dw .song0ch3loop
.song0ch4:
	.db $fb, $08
.song0ch4loop:
	.db $fb, $08, $f7, $87, $fb, $08, $f7, $87, $fb, $08, $f7, $87, $fb, $08, $f7, $87, $fd
	.dw .song0ch4loop
