;this file for FamiStudio Sound Engine generated by FamiStudio

revenge_of_the_pha_music_data:
	.db 1
	.dw .instruments
	.dw .samples-100
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,.song0ch5,.song0ch6,.song0ch7,307,256

.instruments:
	.dw .env21,.env7,.env14,.env24
	.dw .env21,.env12,.env14,.env24
	.dw .env21,.env27,.env14,.env24
	.dw .env2,.env1,.env14,.env18
	.dw .env5,.env0,.env19,.env18
	.dw .env20,.env11,.env19,.env18
	.dw .env13,.env23,.env19,.env18
	.dw .env5,.env10,.env19,.env18
	.dw .env16,.env8,.env19,.env18
	.dw .env22,.env15,.env25,.env18
	.dw .env5,.env0,.env3,.env18
	.dw .env16,.env17,.env19,.env18
	.dw .env2,.env1,.env9,.env18
	.dw .env5,.env0,.env19,.env18
	.dw .env5,.env10,.env19,.env18
	.dw .env5,.env0,.env4,.env18
	.dw .env26,.env0,.env6,.env18
	.dw .env21,.env0,.env28,.env24

.samples:
	.db $00+LOW(FAMISTUDIO_DPCM_PTR),$08,$0f,$40	;25 (SMB3_$E000.dmc)
	.db $03+LOW(FAMISTUDIO_DPCM_PTR),$14,$0f,$40	;26 (SMB3_$F280.dmc)
	.db $09+LOW(FAMISTUDIO_DPCM_PTR),$34,$0f,$40	;27 (SMB3_$D800.dmc)

.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $cc,$d1,$c0,$00,$02
.env2:
	.db $00,$cb,$cd,$cf,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$11
.env3:
	.db $c2,$c1,$00,$01
.env4:
	.db $c7,$c3,$00,$01
.env5:
	.db $04,$cf,$7f,$00,$01
.env6:
	.db $c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$03,$c1,$06,$c0,$00,$0b
.env7:
	.db $c0,$02,$c3,$c3,$c3,$00,$00
.env8:
	.db $c0,$ca,$cb,$00,$02
.env9:
	.db $c7,$02,$c3,$00,$02
.env10:
	.db $cc,$c1,$c0,$00,$02
.env11:
	.db $be,$bf,$00,$01
.env12:
	.db $c0,$02,$c4,$c4,$c4,$00,$00
.env13:
	.db $00,$c3,$c6,$c8,$ca,$cb,$c9,$ca,$c7,$c9,$c7,$c8,$c6,$c7,$c7,$c5,$c7,$c6,$c5,$c4,$c5,$c4,$c5,$c3,$c4,$c3,$c2,$c4,$c2,$c2,$c1,$c2,$c3,$c1,$c2,$c1,$02,$c0,$c1,$c0,$00,$27
.env14:
	.db $c2,$02,$c1,$00,$02
.env15:
	.db $bf,$c0,$00,$01
.env16:
	.db $00,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$00,$07
.env17:
	.db $c0,$c1,$c5,$00,$02
.env18:
	.db $00,$c0,$7f,$00,$01
.env19:
	.db $7f,$00,$00
.env20:
	.db $00,$c4,$c6,$c5,$c4,$c3,$c1,$c0,$00,$07
.env21:
	.db $00,$c8,$cc,$cf,$ce,$cd,$cc,$cb,$ca,$00,$08
.env22:
	.db $00,$c7,$cc,$cf,$00,$03
.env23:
	.db $bb,$bd,$be,$bf,$c0,$c0,$c1,$02,$c0,$00,$04
.env24:
	.db $80,$d4,$b4,$ba,$be,$c4,$c2,$c1,$c0,$bf,$be,$bc,$bc,$be,$bf,$c0,$c1,$c2,$c4,$00,$05
.env25:
	.db $c2,$c1,$c0,$00,$02
.env26:
	.db $00,$cf,$cd,$cc,$cb,$ca,$c9,$c9,$ca,$cb,$cd,$ce,$ce,$cd,$00,$04
.env27:
	.db $c0,$02,$c5,$c5,$c5,$00,$00
.env28:
	.db $c2,$c1,$c1,$c0,$00,$03
.env29:
	.db $00,$c0,$bd,$bb,$ba,$bb,$be,$c2,$c5,$c6,$c5,$c3,$00,$01
.env30:
	.db $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
.env31:
	.db $00,$c0,$bb,$b8,$b7,$b9,$bd,$c3,$c7,$c9,$c8,$c5,$00,$01
.env32:
	.db $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
.env33:
	.db $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
.env34:
	.db $00,$c0,$bd,$c0,$c3,$00,$01
.song0ch0:
.song0ref1:
	.db $79, $63, LOW(.env18), HIGH(.env18), $64, $92
.song0ref7:
	.db $2f, $81, $6b, $02, $2f, $74, $2f, $79
.song0ref15:
	.db $2d, $83, $6b, $02, $81, $2a, $83, $6b, $02, $81, $2b, $83, $6b, $02, $81, $29, $62, $61, $fa, $29, $2a, $81, $62, $2a
	.db $87, $63, LOW(.env29), HIGH(.env29), $8d, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0b
	.dw .song0ref7
.song0ref54:
	.db $6b, $02, $81, $2f, $6b, $02, $81, $32, $85, $63, LOW(.env29), HIGH(.env29), $85, $62, $61, $10, $32, $30, $31, $63, LOW(.env18)
	.db HIGH(.env18), $64, $85, $63, LOW(.env29), HIGH(.env29), $85, $6b, $02, $81
.song0ch0loop:
	.db $79, $63, LOW(.env18), HIGH(.env18), $64, $92, $25, $6b, $02, $81, $25, $6b, $02, $81, $2d, $83, $6b, $02, $81, $2b, $83
	.db $6b, $02, $81, $28, $83, $6b, $02, $81, $29, $62, $61, $fa, $29, $2a, $81, $62, $2a, $87, $63, LOW(.env29), HIGH(.env29)
	.db $8d, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0b
	.dw .song0ref7
	.db $6b, $02, $81, $2f, $6b, $02, $81, $32, $85, $63, LOW(.env29), HIGH(.env29), $85, $62, $61, $10, $32, $30, $34, $63, LOW(.env18)
	.db HIGH(.env18), $64, $85, $63, LOW(.env29), HIGH(.env29), $85, $6b, $02
.song0ref169:
	.db $81, $76, $63, LOW(.env18), HIGH(.env18), $64, $80, $2a, $bd, $82, $25, $bd, $63, LOW(.env18), HIGH(.env18), $64, $80
	.db $2a, $bd, $82, $25, $bd, $63, LOW(.env18), HIGH(.env18), $64, $80, $2a, $bd, $82, $25, $bd, $63, LOW(.env18), HIGH(.env18)
	.db $64, $80, $2a, $bd, $26, $bd, $00, $85, $78
.song0ref213:
	.db $63, LOW(.env18), HIGH(.env18), $64, $94, $38, $83, $6b, $02, $81, $36, $38, $36, $6b, $02, $81, $34, $83, $6b, $02, $81
	.db $32, $81, $63, LOW(.env30), HIGH(.env30), $81, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $31, $83, $6b, $02
	.db $81, $2f, $83, $6b, $02, $81, $2e, $81, $74, $81, $6b, $02, $81, $78
.song0ref265:
	.db $2e, $83, $6b, $02, $81, $31, $83, $6b, $02, $81, $32, $83, $6b, $02, $81, $34, $85, $63, LOW(.env29), HIGH(.env29), $83
	.db $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83, $71, $85, $68, $02, $8b, $74
.song0ref305:
	.db $31, $83, $6b, $02, $81, $32, $83, $6b, $02, $81, $34, $83, $6b, $02, $81, $36, $81, $63, LOW(.env30), HIGH(.env30), $81
	.db $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $34, $83, $6b, $02, $81, $36, $83, $6b, $02, $81, $37, $81, $72, $81
	.db $6b, $02, $81, $74
.song0ref351:
	.db $38, $37, $38, $6b, $02, $81, $34, $83, $6b, $02, $81, $31, $83, $6b, $02, $81, $2d, $83, $6b, $02, $81, $2c, $85, $63
	.db LOW(.env29), HIGH(.env29), $87, $73, $85, $81, $72, $83, $68, $00, $81, $78
.song0ref387:
	.db $63, LOW(.env18), HIGH(.env18), $64, $2c, $83, $6b, $02, $81, $2d, $83, $6b, $02, $81, $2f, $85, $63, LOW(.env31), HIGH(.env31)
	.db $85, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $2d, $83, $6b, $02, $81, $2f, $83, $6b, $02, $81, $31, $85, $63
	.db LOW(.env29), HIGH(.env29), $85, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $2f, $83, $6b, $02, $81, $31, $83
	.db $6b, $02, $81, $32, $85, $63, LOW(.env29), HIGH(.env29), $87, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83
	.db $71, $85, $68, $00, $81, $74, $63, LOW(.env18), HIGH(.env18), $64, $2b, $83, $6b, $02, $81, $2d, $83, $6b, $02, $81, $2f
	.db $83, $6b, $02, $81, $75, $31, $83, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $32, $83, $6b, $02, $81, $34, $83
	.db $6b, $02, $81, $36, $83, $6b, $02, $81, $39, $83, $6b, $01, $81, $73, $39, $6b, $01, $81, $6b, $01, $39, $00, $75, $3b
	.db $83, $6b, $01, $81, $73, $3b, $6b, $01, $81, $6b, $01, $3b, $00, $75, $61, $fb, $36, $38, $81, $62, $38, $81, $63, LOW(.env32)
	.db HIGH(.env32), $83, $74, $83, $63, LOW(.env33), HIGH(.env33), $81, $73, $85, $72, $85, $71
	.db $ff, $11
	.dw .song0ref169
	.db $ff, $14
	.dw .song0ref1
	.db $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0b
	.dw .song0ref7
	.db $ff, $0b
	.dw .song0ref54
	.db $fd
	.dw .song0ch0loop
.song0ch1:
	.db $68, $03, $00, $87, $74, $63, LOW(.env18), HIGH(.env18), $64, $92, $2f, $81, $6b, $02, $2f, $72, $2f, $74
	.db $ff, $10
	.dw .song0ref15
.song0ref608:
	.db $63, LOW(.env18), HIGH(.env18), $64
.song0ref612:
	.db $2f, $81, $6b, $02, $2f, $72, $2f, $74, $2d, $83, $6b, $02, $81, $2a, $83, $6b, $02, $81, $2b, $6b, $02, $81, $2f, $6b
	.db $02, $81, $32, $85, $63, LOW(.env29), HIGH(.env29), $85, $62, $61, $0c, $32, $30, $31, $63, LOW(.env18), HIGH(.env18)
	.db $64, $83
.song0ch1loop:
	.db $76, $92, $21, $6b, $02, $81, $21, $6b, $02, $81, $23, $83, $6b, $02, $81, $21, $83, $6b, $02, $81, $1f, $83, $6b, $02
	.db $81, $1e, $8d, $63, LOW(.env29), HIGH(.env29), $8d, $6b, $02, $81, $74, $2a, $85, $6b, $02, $81
	.db $ff, $0f
	.dw .song0ref608
	.db $81, $68, $00, $81, $76, $63, LOW(.env18), HIGH(.env18), $64, $86, $34, $81, $37, $81, $39, $81, $3b, $81
.song0ref717:
	.db $63, LOW(.env18), HIGH(.env18), $64, $84, $25, $bd, $80, $29, $bd, $63, LOW(.env18), HIGH(.env18), $64, $84, $25, $bd
	.db $80, $29, $bd, $63, LOW(.env18), HIGH(.env18), $64, $84, $25, $bd, $80, $29, $bd, $63, LOW(.env18), HIGH(.env18), $64
	.db $84, $25, $bd, $80, $29, $bd, $68, $02, $00, $8f, $74
	.db $ff, $16
	.dw .song0ref213
	.db $72, $81, $6b, $02, $81, $74
	.db $ff, $0b
	.dw .song0ref265
	.db $63, LOW(.env29), HIGH(.env29), $89, $73, $87, $72, $83, $81, $71, $83, $68, $00, $81, $78, $63, LOW(.env18), HIGH(.env18)
	.db $64
	.db $ff, $15
	.dw .song0ref305
	.db $74, $81, $6b, $02, $81, $78
	.db $ff, $10
	.dw .song0ref351
	.db $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $81, $68, $02, $81, $71, $89, $74
	.db $ff, $1d
	.dw .song0ref387
	.db $73, $87, $72, $85, $81, $71, $83, $68, $00, $81, $78, $63, LOW(.env18), HIGH(.env18), $64, $31, $83, $6b, $02, $81, $32
	.db $83, $6b, $02, $81, $34, $83, $6b, $02, $81, $79, $36, $83, $6b, $02, $81, $63, LOW(.env18), HIGH(.env18), $64, $37, $83
	.db $6b, $02, $81, $39, $83, $6b, $02, $81, $3b, $83, $6b, $02, $81, $3e, $83, $6b, $01, $81, $74, $3e, $6b, $01, $81, $6b
	.db $01, $3e, $00, $79, $3e, $83, $6b, $01, $81, $74, $3e, $6b, $01, $81, $6b, $01, $3e, $00, $79, $61, $f9, $3b, $3d, $62
	.db $3d, $83, $63, LOW(.env32), HIGH(.env32), $83, $78, $83, $77, $63, LOW(.env33), HIGH(.env33), $83, $76, $83, $75, $83
	.db $74, $83, $76
	.db $ff, $10
	.dw .song0ref717
	.db $68, $03, $00, $87, $74, $63, LOW(.env18), HIGH(.env18), $64, $92
	.db $ff, $0b
	.dw .song0ref612
	.db $83, $6b, $02, $81, $29, $62, $61, $fa, $29, $2a, $81, $62, $2a, $87, $63, LOW(.env29), HIGH(.env29), $8d, $6b, $02, $81
	.db $ff, $14
	.dw .song0ref608
	.db $fd
	.dw .song0ch1loop
.song0ch2:
.song0ref979:
	.db $8e
.song0ref980:
	.db $12, $83, $6b, $01, $81, $1e, $83, $6b, $01, $81, $1e, $6b, $01, $81, $6b, $01, $1e, $00, $13, $83, $6b, $01, $81, $12
	.db $83, $6b, $01, $81, $1e, $81, $6b, $02, $1e, $00, $10, $83, $6b, $01, $81, $1c, $81, $6b, $02, $1c, $00
	.db $ff, $10
	.dw .song0ref980
.song0ref1028:
	.db $1a, $81, $6b, $02, $1a, $00, $11, $83, $6b, $01, $81, $19, $81, $6b, $02, $19, $00
.song0ch2loop:
	.db $ff, $1b
	.dw .song0ref979
	.db $ff, $10
	.dw .song0ref980
	.db $ff, $0b
	.dw .song0ref1028
	.db $ff, $1b
	.dw .song0ref980
.song0ref1058:
	.db $0d, $83, $6b, $01, $81, $19, $83, $6b, $01, $81, $19, $6b, $01, $81, $6b, $01, $19, $00, $0e, $83, $6b, $01, $81, $0d
	.db $83, $6b, $01, $81, $11, $81, $6b, $02, $1d, $00, $14, $88, $15, $81, $6b, $01, $81, $8e, $13, $81, $6b, $02, $13, $00
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $1c
	.dw .song0ref1058
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $1c
	.dw .song0ref1058
	.db $ff, $1b
	.dw .song0ref980
.song0ref1121:
	.db $0e, $83, $6b, $01, $81, $1a, $83, $6b, $01, $81, $1a, $6b, $01, $81, $6b, $01, $1a, $00
.song0ref1139:
	.db $0e, $83, $6b, $01, $81, $12, $83, $6b, $01, $81, $13, $83, $6b, $01, $81, $17, $83, $6b, $01, $81, $18, $83, $6b, $01
	.db $81, $0d, $83, $6b, $01, $81, $0d, $6b, $01, $81, $6b, $01, $0d, $00, $8f
.song0ref1178:
	.db $0d, $83, $6b, $01, $81, $0d, $83, $6b, $01, $81, $0d, $6b, $01, $81, $6b, $01, $0d, $00, $87, $0d, $83, $6b, $01, $81
	.db $0d, $6b, $01, $81, $6b, $01, $0d, $00, $8f, $88, $2e, $83, $6b, $01, $81
.song0ref1217:
	.db $31, $83, $6b, $01, $81, $32, $83, $6b, $01, $81, $34, $85, $63, LOW(.env29), HIGH(.env29), $8b, $62, $61, $40, $34, $29
	.db $6b, $01, $81, $63, LOW(.env18), HIGH(.env18), $64, $00, $62, $29, $8b, $8e
	.db $ff, $13
	.dw .song0ref1178
	.db $88, $38, $37, $38, $6b, $01, $81, $34, $83, $6b, $01, $81, $31, $83, $6b, $01, $81, $2d, $83, $6b, $01, $81, $2c, $85
	.db $63, LOW(.env29), HIGH(.env29), $8b, $62, $61, $44, $2c, $24, $6b, $01, $81, $63, LOW(.env18), HIGH(.env18), $64, $00
	.db $62, $24, $83, $8e
	.db $ff, $12
	.dw .song0ref1178
	.db $95, $6b, $01, $81, $88
	.db $ff, $0e
	.dw .song0ref1217
	.db $8e
	.db $ff, $0b
	.dw .song0ref1178
	.db $0e, $83, $6b, $01, $81, $0e, $6b, $01, $81, $6b, $01, $0e, $00, $0e, $83, $6b, $01, $81, $0e, $6b, $01, $81, $6b, $01
	.db $0e, $00
.song0ref1339:
	.db $0d, $83, $6b, $01, $81, $19, $83, $6b, $01, $81, $11, $83, $6b, $01, $81, $1d, $83, $6b, $01, $81
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $1c
	.dw .song0ref1058
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $1c
	.dw .song0ref1058
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $1c
	.dw .song0ref1058
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $19
	.dw .song0ref1121
	.db $ff, $1b
	.dw .song0ref980
	.db $ff, $10
	.dw .song0ref980
	.db $ff, $0b
	.dw .song0ref1028
	.db $fd
	.dw .song0ch2loop
.song0ch3:
.song0ref1395:
	.db $90, $21, $81, $8a, $2d, $81, $2d, $81
.song0ref1403:
	.db $2d, $81, $96, $26, $81, $8a, $2d, $81, $2d, $81, $2d, $81
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
.song0ch3loop:
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $0f
	.dw .song0ref1395
.song0ref1437:
	.db $8c, $2a, $8b, $77, $8a
.song0ref1442:
	.db $2d, $81, $7f, $96, $26, $85, $8a, $2d, $81, $77, $2d, $81, $7f, $90, $21, $85, $8a, $2d, $81, $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
.song0ref1513:
	.db $77, $2d, $81, $7f, $96, $26, $85, $8a, $2d, $81, $77, $2d, $81, $7c, $88, $30, $6e, $fb, $70, $89, $6e, $f9, $40, $83
	.db $7c, $6e, $f9, $90, $61, $f0, $2b, $24, $81, $7c, $6e, $f9, $90, $61, $f0, $2a, $23, $81, $7c, $6e, $f9, $90, $61, $f0
	.db $29, $22, $81, $7b, $61, $f0, $28, $24, $7f, $8c, $2a, $8f
.song0ref1573:
	.db $96, $23, $81, $6e, $f9, $70, $8b, $7f, $90, $21, $81, $6e, $f9, $c0, $83, $7f, $21, $81, $6e, $f9, $c0, $83, $7f, $96
	.db $23, $81, $6e, $f9, $70, $8b, $7f, $90, $21, $81, $6e, $f9, $70, $8b, $7f
	.db $ff, $0f
	.dw .song0ref1573
	.db $7f
	.db $ff, $0f
	.dw .song0ref1573
	.db $7f
	.db $ff, $0f
	.dw .song0ref1573
	.db $7f
	.db $ff, $0f
	.dw .song0ref1573
	.db $7f
	.db $ff, $0f
	.dw .song0ref1573
	.db $7f
	.db $ff, $0b
	.dw .song0ref1573
	.db $6e, $f9, $80, $89, $7c, $8c, $29, $8d, $7d, $2b, $8d, $7f, $2a, $8f, $96, $26, $81, $8a, $2d, $81, $2d, $81, $2d
	.db $ff, $0e
	.dw .song0ref1437
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $77
	.db $ff, $0c
	.dw .song0ref1442
	.db $ff, $13
	.dw .song0ref1513
	.db $8b, $8a
	.db $ff, $0a
	.dw .song0ref1403
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
	.db $ff, $10
	.dw .song0ref1395
	.db $fd
	.dw .song0ch3loop
.song0ch4:
	.db $fb, $03
.song0ref1735:
	.db $fb, $04, $88
.song0ref1738:
	.db $19, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
.song0ref1748:
	.db $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $19, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $19, $fb, $03, $1a, $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04
	.db $ff, $17
	.dw .song0ref1738
	.db $fb, $03, $81, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a
	.db $fb, $03, $81
.song0ch4loop:
	.db $ff, $20
	.dw .song0ref1735
	.db $fb, $04
	.db $ff, $17
	.dw .song0ref1738
	.db $fb, $03, $81, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81
.song0ref1888:
	.db $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $1a
.song0ref1915:
	.db $fb, $03, $81
.song0ref1918:
	.db $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81
	.db $fb, $04, $81, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $1a
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $0d
	.dw .song0ref1915
.song0ref2008:
	.db $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81
	.db $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81
	.db $fb, $04, $81, $fb, $03, $81
.song0ref2062:
	.db $fb, $04, $81
.song0ref2065:
	.db $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a
	.db $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $19, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $19
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0f
	.dw .song0ref2065
	.db $ff, $11
	.dw .song0ref2062
	.db $ff, $0b
	.dw .song0ref2065
	.db $fb, $04, $1b, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $1b, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81, $fb, $04, $81, $fb, $03, $81
	.db $fb, $04, $19, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $1a, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81
	.db $fb, $04, $19, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $1a
	.db $ff, $1a
	.dw .song0ref1888
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $11
	.dw .song0ref1915
	.db $ff, $0f
	.dw .song0ref1918
	.db $ff, $0d
	.dw .song0ref1915
	.db $ff, $12
	.dw .song0ref2008
	.db $ff, $1c
	.dw .song0ref1748
	.db $fb, $04
	.db $ff, $17
	.dw .song0ref1738
	.db $fb, $03, $81, $fb, $04, $1b, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a, $fb, $03, $81, $fb, $04, $1a
	.db $fb, $03, $81, $fd
	.dw .song0ch4loop
.song0ch5:
	.db $75, $a2, $19, $68, $01, $bd, $19, $9d, $1e, $8d, $1d, $8d
.song0ch5loop:
	.db $75, $a2, $19, $68, $01, $bd, $19, $9d, $1e, $8d, $1d, $8d
.song0ref2347:
	.db $63, LOW(.env18), HIGH(.env18), $64, $00, $85, $7c, $6e, $fd, $80, $a0, $25, $8d, $7c, $6e, $fe, $50, $2b, $9d, $7c, $6e
	.db $fd, $60, $2b, $95, $7c, $6e, $fe, $50, $29, $9d, $7c, $6e, $fe, $50, $25, $8d, $8f, $7c, $6e, $fd, $60, $2a, $95, $7c
	.db $6e, $fd, $60, $2a, $95, $7c, $6e, $fd, $60, $2d, $95, $7c, $6e, $fd, $80, $25, $8d, $7c, $6e, $fe, $50, $31, $95, $87
	.db $7c, $6e, $fd, $a0
.song0ref2420:
	.db $25, $85, $7c, $6e, $fd, $a0, $2a, $85, $7c, $6e, $fd, $80, $2b, $8d, $7c, $6e, $fd, $80, $2a, $8d, $7c, $6e, $fd, $a0
	.db $2b, $85, $7c, $6e, $fd, $60, $2d, $95, $79, $6e, $fd, $70, $63, LOW(.env34), HIGH(.env34), $31, $85, $7c, $6e, $fd, $60
	.db $63, LOW(.env18), HIGH(.env18), $64, $26, $95, $79, $6e, $fd, $50, $63, LOW(.env34), HIGH(.env34), $29, $85, $85, $6e
	.db $fa, $40, $81, $7c, $6e, $fd, $a0, $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0a
	.dw .song0ref2420
.song0ref2496:
	.db $7c, $6e, $fd, $80, $2d, $8d, $7c, $6e, $fd, $80, $29, $8d, $7c, $6e, $fd, $a0, $30, $85, $7c, $6e, $fd, $a0, $31, $85
	.db $7c, $6e, $fd, $a0, $35, $85, $7c, $6e, $fd, $a0, $36, $85, $7c, $6e, $fd, $80, $38, $8b, $81, $71
.song0ref2540:
	.db $28, $8d, $72, $25, $8d, $73, $26, $8d, $74, $2c, $8d, $73, $26, $8d, $72, $25, $8d, $76, $26, $8d, $77, $25, $8d, $76
.song0ref2564:
	.db $28, $8d, $75, $25, $8d, $26, $8d, $74, $2c, $8d, $75, $26, $8d, $25, $8d, $71, $26, $8d, $00, $8d
	.db $ff, $14
	.dw .song0ref2540
	.db $2c, $85, $2b, $83, $6a, $00, $73, $9e, $35, $75, $36, $83, $6b, $01, $81, $72, $36, $6b, $01, $81, $6b, $01, $36, $00
	.db $75, $36, $83, $6b, $01, $81, $72, $36, $6b, $01, $81, $6b, $01, $36, $00, $75, $35, $85, $63, LOW(.env32), HIGH(.env32)
	.db $83, $74, $83, $63, LOW(.env33), HIGH(.env33), $81, $73, $85, $72, $85, $71, $81
	.db $ff, $2c
	.dw .song0ref2347
	.db $7c, $6e, $fd, $a0, $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0a
	.dw .song0ref2420
	.db $ff, $0c
	.dw .song0ref2496
	.db $75, $a2, $19, $68, $01, $bd, $19, $9d, $1e, $8d, $1d, $8d, $fd
	.dw .song0ch5loop
.song0ch6:
.song0ref2677:
	.db $75, $a2, $1e, $68, $01, $bd, $1e, $99, $76, $21, $77, $23, $78, $26, $8d, $25, $8d
.song0ch6loop:
	.db $75, $68, $01, $a2, $1e, $bd, $1e, $99, $76, $21, $77, $23, $78, $26, $8d, $28, $8d, $76, $68, $00, $98, $3d
.song0ref2717:
	.db $8d, $7c, $6e, $fd, $60, $a0, $2a, $95, $7c, $6e, $fd, $60, $2a, $95, $7c, $6e, $fe, $50, $2d, $9d, $7c, $6e, $fd, $30
	.db $26, $9d, $87, $7c, $6e, $fd, $80, $25, $8d, $7c, $6e, $fe, $50, $2b, $9d, $7c, $6e, $fd, $60, $2b, $95, $7c, $6e, $fd
	.db $80, $29, $8d, $7c, $6e, $fd, $30, $30, $9d, $87, $7a, $6e, $fd, $80
.song0ref2779:
	.db $21, $85, $7a, $6e, $fd, $80, $25, $85, $7a, $6e, $fd, $60, $25, $8d, $7a, $6e, $fd, $60, $25, $8d, $7a, $6e, $fd, $80
	.db $2a, $85, $7a, $6e, $fd, $80, $29, $85, $79, $6e, $fd, $70, $63, LOW(.env34), HIGH(.env34), $35, $85, $7c, $6e, $fd, $60
	.db $63, LOW(.env18), HIGH(.env18), $64, $29, $95, $79, $6e, $fd, $70, $63, LOW(.env34), HIGH(.env34), $2d, $85, $7c, $6e
	.db $fd, $70, $63, LOW(.env18), HIGH(.env18), $64, $25, $8d, $85, $6e, $fa, $60, $81, $7a, $6e, $fd, $80, $63, LOW(.env18)
	.db HIGH(.env18), $64
	.db $ff, $0a
	.dw .song0ref2779
.song0ref2865:
	.db $7a, $6e, $fd, $40, $29, $95, $7c, $6e, $fd, $a0, $25, $85, $6e, $fd, $80, $2a, $85, $7a, $6e, $fd, $80, $2b, $85, $7a
	.db $6e, $fd, $80, $2f, $85, $7a, $6e, $fd, $80, $30, $85, $7a, $6e, $fd, $60, $31, $8b, $81, $68, $fe
	.db $ff, $0e
	.dw .song0ref2564
	.db $68, $fe, $00, $8d
	.db $ff, $0e
	.dw .song0ref2540
	.db $77, $68, $fe, $25, $8d, $76, $68, $fe
	.db $ff, $0e
	.dw .song0ref2564
	.db $68, $fe, $00, $8d, $28, $8d, $72, $25, $8d, $73, $2c, $85, $2b, $83, $6a, $00, $9e, $31, $75, $68, $01, $32, $83, $6b
	.db $01, $81, $72, $32, $6b, $01, $81, $6b, $01, $32, $00, $75, $32, $83, $6b, $01, $81, $72, $32, $6b, $01, $81, $6b, $01
	.db $32, $00, $75, $61, $fb, $2f, $31, $83, $62, $31, $63, LOW(.env32), HIGH(.env32), $83, $74, $83, $63, LOW(.env33), HIGH(.env33)
	.db $81, $73, $85, $72, $85, $71, $81, $63, LOW(.env18), HIGH(.env18), $64, $00
	.db $ff, $2b
	.dw .song0ref2717
	.db $7a, $6e, $fd, $80, $63, LOW(.env18), HIGH(.env18), $64
	.db $ff, $0a
	.dw .song0ref2779
	.db $ff, $0c
	.dw .song0ref2865
	.db $ff, $0a
	.dw .song0ref2677
	.db $fd
	.dw .song0ch6loop
.song0ch7:
.song0ref3032:
	.db $7a, $9c
.song0ref3034:
	.db $12, $83, $6b, $01, $81, $1e, $83, $6b, $01, $81, $74, $1e, $6b, $01, $81, $6b, $01, $1e, $00, $7a, $13, $83, $6b, $01
	.db $81, $12, $83, $6b, $01, $81, $1e, $81, $74, $6b, $02, $1e, $00, $7a, $10, $83, $6b, $01, $81, $1c, $81, $74, $6b, $02
	.db $1c, $00, $7a, $12, $83, $6b, $01, $81, $1e, $83, $6b, $01, $81, $74, $1e, $6b, $01, $81, $71, $6b, $01, $1e, $00, $7a
	.db $13, $83, $6b, $01, $81, $12, $83, $6b, $01, $81, $1a, $81, $74, $6b, $02, $1a, $00, $7a, $11, $83, $6b, $01, $81, $19
	.db $81, $74, $6b, $02, $19, $00
.song0ch7loop:
	.db $ff, $36
	.dw .song0ref3032
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
.song0ref3144:
	.db $7a, $0d, $83, $6b, $01, $81, $19, $83, $6b, $01, $81, $74, $19, $6b, $01, $81, $71, $6b, $01, $19, $00, $7a, $0e, $83
	.db $6b, $01, $81, $0d, $83, $6b, $01, $81, $11, $81, $74, $6b, $02, $1d, $6b, $01, $00, $7a, $14, $9a, $15, $81, $6b, $01
	.db $81, $9c, $13, $81, $74, $6b, $02, $13, $00, $7a
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $1c
	.dw .song0ref3144
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $1c
	.dw .song0ref3144
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
.song0ref3219:
	.db $7a, $0e, $83, $6b, $01, $81, $1a, $83, $6b, $01, $81, $74, $1a, $6b, $01, $81, $71, $6b, $01, $1a, $00, $7a
	.db $ff, $12
	.dw .song0ref1139
.song0ref3244:
	.db $74, $0d, $6b, $01, $81, $6b, $01, $0d, $00, $8f, $7a, $0d, $83, $6b, $01, $81, $0d, $83, $6b, $01, $81, $74, $0d, $6b
	.db $01, $81, $6b, $01, $0d, $00, $87, $7a, $0d, $83, $6b, $01, $81
	.db $ff, $13
	.dw .song0ref3244
	.db $ff, $13
	.dw .song0ref3244
	.db $ff, $13
	.dw .song0ref3244
	.db $ff, $13
	.dw .song0ref3244
	.db $ff, $13
	.dw .song0ref3244
	.db $ff, $10
	.dw .song0ref3244
	.db $7a, $0e, $83, $6b, $01, $81, $74, $0e, $6b, $01, $81, $6b, $01, $0e, $00, $7a, $0e, $83, $6b, $01, $81, $74, $0e, $6b
	.db $01, $81, $6b, $01, $0e, $00, $7a
	.db $ff, $0c
	.dw .song0ref1339
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $1c
	.dw .song0ref3144
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $1c
	.dw .song0ref3144
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $1c
	.dw .song0ref3144
	.db $7a
	.db $ff, $1b
	.dw .song0ref3034
	.db $ff, $0a
	.dw .song0ref3219
	.db $7a
	.db $ff, $0f
	.dw .song0ref1139
	.db $ff, $36
	.dw .song0ref3034
	.db $fd
	.dw .song0ch7loop
