; This file for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_megami_tensei_ii:
	.db 1
	.dw .instruments
	.dw .instruments_exp
	.dw .samples-4
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,.song0ch5,.song0ch6,.song0ch7,.song0ch8
	.db LOW(.tempo_env_10_mid), HIGH(.tempo_env_10_mid), 0, 0

.instruments:
	.dw .env2,.env0,.env11,.env9
	.dw .env16,.env0,.env7,.env6
	.dw .env10,.env0,.env7,.env6
	.dw .env17,.env14,.env7,.env9

.instruments_exp:
	.dw .env1, .env0, .env6
	.db $10, $08
	.dw .env8
	.db $00, $00, $00, $00, $00, $00
	.dw .env4, .env0, .env6
	.db $00, $10
	.dw .env5
	.db $00, $00, $00, $00, $00, $00
	.dw .env3, .env0, .env6
	.db $20, $10
	.dw .env13
	.db $00, $00, $00, $00, $00, $00
	.dw .env15, .env0, .env12
	.db $20, $10
	.dw .env13
	.db $00, $00, $00, $00, $00, $00

.samples:
.env0:
	.db $c0,$7f,$00,$00
.env1:
	.db $00,$c4,$c4,$c3,$c2,$c0,$00,$05
.env2:
	.db $09,$c5,$c5,$c4,$c4,$c3,$c3,$00,$06,$c2,$c2,$c1,$c1,$c0,$04,$c2,$02,$c1,$02,$c0,$00,$13
.env3:
	.db $04,$c7,$00,$01,$c6,$0b,$c5,$0b,$c4,$0b,$c3,$0b,$c2,$0b,$c1,$0b,$c0,$00,$10
.env4:
	.db $00,$c5,$02,$c4,$c3,$03,$c2,$03,$c1,$03,$c0,$00,$0a
.env5:
	.db $ff,$f0,$ff,$0f,$00,$f0,$ff,$ff,$00,$00,$00,$00,$00,$00,$00,$00
.env6:
	.db $00,$c0,$7f,$00,$01
.env7:
	.db $7f,$00,$00
.env8:
	.db $db,$fe,$ef,$bd,$35,$12,$21,$53
.env9:
	.db $00,$bf,$7f,$00,$01
.env10:
	.db $00,$c8,$c8,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0d
.env11:
	.db $c1,$7f,$00,$00
.env12:
	.db $00,$bc,$7f,$00,$01
.env13:
	.db $21,$22,$12,$42,$ec,$fd,$de,$cc,$dc,$de,$4a,$12,$62,$ea,$dc,$26
.env14:
	.db $c0,$bc,$00,$01
.env15:
	.db $04,$c4,$00,$01,$c3,$0b,$c2,$0b,$c1,$0b,$c0,$00,$0a
.env16:
	.db $00,$c5,$c0,$00,$02
.env17:
	.db $00,$cf,$cf,$c0,$00,$03
.tempo_env_10_mid:
	.db $03,$04,$06,$05,$05,$05,$80
.song0ch0:
.song0ref1:
	.db $80
.song0ref2:
	.db $1f, $a5, $1f, $89, $f9, $99, $00, $91, $1d, $89, $f9, $99, $00, $91, $1b, $89, $f9, $99, $00, $91, $1b, $89, $f9, $99
	.db $00, $91, $1d, $a5
.song0ch0loop:
	.db $6a, LOW(.tempo_env_10_mid), HIGH(.tempo_env_10_mid)
	.db $ff, $1c
	.dw .song0ref1
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $6b, $1b, $a5, $1b, $89, $f9, $99, $00, $93, $1d, $b7, $1b, $a5, $1b, $89, $f9, $99, $00, $91, $1e, $b9, $6b
	.db $ff, $1c
	.dw .song0ref2
	.db $fd
	.dw .song0ch0loop
.song0ch1:
.song0ref117:
	.db $80
.song0ref118:
	.db $1a, $a5, $1a, $89, $f9, $99, $00, $91, $18, $89, $f9, $99, $00, $91, $16, $89, $f9, $99, $00, $91, $16, $89, $f9, $99
	.db $00, $91, $18, $a5
.song0ch1loop:
	.db $ff, $1c
	.dw .song0ref117
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $ff, $1c
	.dw .song0ref118
	.db $16, $a5, $16, $89, $f9, $99, $00, $93, $18, $b7, $16, $a5, $16, $89, $f9, $99, $00, $93, $1a, $b7
	.db $ff, $1c
	.dw .song0ref118
	.db $fd
	.dw .song0ch1loop
.song0ch2:
	.db $f7, $f7, $cf
.song0ch2loop:
	.db $f7, $f7, $cf, $86
.song0ref223:
	.db $25, $87, $00, $9b, $25, $87, $00, $9b, $25, $87, $00, $9b, $25, $87, $00, $9b, $25, $87, $00, $9b, $25, $87, $00, $9b
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
	.db $ff, $18
	.dw .song0ref223
.song0ref268:
	.db $25, $87, $00, $9b, $2d, $87, $00, $9b, $25, $87, $00, $87, $25, $87, $00, $87, $2d, $87, $00, $9b, $25, $87, $00, $9b
	.db $2d, $87, $00, $9b, $25, $87, $00, $87, $25, $87, $00, $87, $2d, $87, $00, $9b
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $ff, $28
	.dw .song0ref268
	.db $f7, $f7, $cf, $fd
	.dw .song0ch2loop
.song0ch3:
	.db $f7, $f7, $cf
.song0ch3loop:
	.db $f7, $f7, $cf, $82
.song0ref343:
	.db $0e, $87, $00, $9b, $0e, $87, $00, $9b, $0e, $87, $00, $9b, $0e, $87, $00, $9b, $0e, $87, $00, $9b, $0e, $87, $00, $9b
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
	.db $ff, $18
	.dw .song0ref343
.song0ref388:
	.db $0e, $87, $0e, $87, $0e, $87, $0e, $87, $84, $07, $91, $82, $0e, $87, $0e, $87, $0e, $87, $0e, $87, $0e, $87, $0e, $87
	.db $84, $07, $91, $82, $0e, $87, $0e, $87
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $ff, $1c
	.dw .song0ref388
	.db $00, $f7, $f7, $cd, $fd
	.dw .song0ch3loop
.song0ch4:
	.db $f7, $f7, $cf
.song0ch4loop:
.song0ref476:
	.db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	.db $ff, $15
	.dw .song0ref476
	.db $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.dw .song0ch4loop
.song0ch5:
	.db $f7, $f7, $cf
.song0ch5loop:
	.db $ff, $15
	.dw .song0ref476
	.db $82
.song0ref517:
	.db $1f, $91, $1f, $91, $1f, $91, $1f, $91, $1f, $91, $1f, $91, $1f, $91, $1d, $91, $1b, $91, $1b, $91, $1b, $91, $1b, $91
	.db $1b, $91, $1b, $91, $1d, $91, $1d, $91
	.db $ff, $20
	.dw .song0ref517
	.db $ff, $20
	.dw .song0ref517
	.db $ff, $20
	.dw .song0ref517
	.db $ff, $20
	.dw .song0ref517
	.db $ff, $20
	.dw .song0ref517
	.db $ff, $20
	.dw .song0ref517
	.db $00, $1b, $8f, $1b, $91, $1b, $91, $1b, $91, $1b, $91, $1d, $91, $1d, $91, $1d, $91, $1b, $91, $1b, $91, $1b, $91, $1b
	.db $91, $1b, $91, $1a, $91, $1a, $91, $1a, $91, $00, $f7, $f7, $cd, $fd
	.dw .song0ch5loop
.song0ch6:
	.db $f7, $f7, $cf
.song0ch6loop:
	.db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $80
.song0ref621:
	.db $43, $87, $00, $87, $49, $87, $00, $87, $46, $87, $00, $87, $43, $87, $00, $89, $47, $87, $00, $85, $45, $87, $00, $87
	.db $41, $87, $00, $87, $46, $87, $00, $87, $43, $87, $00, $87, $3f, $87, $00, $87, $46, $87, $00, $87, $43, $87, $00, $87
	.db $3f, $87, $00, $87, $45, $87, $00, $87, $41, $87, $00, $87, $3c, $87, $00, $87
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $ff, $40
	.dw .song0ref621
	.db $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.dw .song0ch6loop
.song0ch7:
	.db $f7, $f7, $cf
.song0ch7loop:
	.db $ff, $15
	.dw .song0ref476
	.db $84, $61, $10, $36, $3e, $9b, $62, $3e, $f7, $af, $3c, $91, $3a, $91, $39, $91, $37, $91, $35, $91, $39, $91, $61, $07
	.db $34, $37, $91, $62, $37, $a5, $32, $f7, $e1, $62, $61, $f9, $32, $28, $a5, $61, $08, $2d, $30, $89, $62, $30, $ad, $61
	.db $09, $30, $32, $85, $62, $32, $b1, $61, $0a, $32, $33, $81, $62, $33, $b5, $61, $0a, $33, $35, $85, $62, $35, $b1, $61
	.db $0c, $35, $37, $85, $62, $37, $9d, $61, $0d, $37, $39, $85, $62, $39, $9d, $61, $0e, $39, $3a, $81, $62, $3a, $b5, $61
	.db $f2, $3a, $39, $81, $62, $39, $b5, $61, $0f, $39, $3c, $89, $62, $3c, $99, $61, $f1, $3c, $3a, $85, $62, $3a, $b1, $61
	.db $f2, $3a, $39, $81, $62, $39, $b5, $62, $61, $f6, $39, $2f, $a5, $61, $10, $36, $3e, $9b, $62, $3e, $f7, $87, $3c, $91
	.db $3a, $91, $39, $91, $3a, $91, $3c, $91, $3e, $91, $3c, $91, $39, $91, $37, $b1, $61, $0f, $37, $3e, $99, $62, $3e, $f7
	.db $cd, $62, $61, $f2, $3e, $34, $a5, $61, $12, $39, $41, $9b, $62, $41, $f7, $87, $3f, $91, $3a, $91, $37, $91, $3a, $91
	.db $3f, $91, $41, $91, $3f, $91, $3a, $91, $3e, $a1, $61, $f0, $3e, $33, $a1, $62, $61, $f0, $3d, $3b, $85, $62, $32, $99
	.db $61, $0e, $32, $3f, $b1, $62, $3f, $a9, $61, $f1, $3f, $36, $a1, $62, $36, $99, $61, $11, $36, $43, $b1, $62, $43, $f7
	.db $bf, $f9, $f7, $8b, $fd
	.dw .song0ch7loop
.song0ch8:
	.db $f7, $f7, $cf
.song0ch8loop:
	.db $ff, $15
	.dw .song0ref476
	.db $8f, $86, $61, $10, $36, $3e, $9b, $3e, $f7, $af, $3c, $91, $3a, $91, $39, $91, $37, $91, $35, $91, $39, $81, $8f, $61
	.db $07, $34, $37, $91, $37, $a5, $32, $f7, $e1, $61, $f9, $32, $28, $95, $8f, $61, $08, $2d, $30, $89, $30, $ad, $61, $09
	.db $30, $32, $85, $32, $b1, $61, $0a, $32, $33, $81, $62, $33, $b5, $61, $0a, $33, $35, $85, $35, $b1, $61, $0c, $35, $37
	.db $85, $37, $9d, $61, $0d, $37, $39, $85, $39, $8d, $8f, $61, $0e, $39, $3a, $81, $62, $3a, $b5, $61, $f2, $3a, $39, $81
	.db $62, $39, $b5, $61, $0f, $39, $3c, $89, $3c, $99, $61, $f1, $3c, $3a, $85, $3a, $b1, $61, $f2, $3a, $39, $81, $62, $39
	.db $b5, $61, $f6, $39, $2f, $95, $8f, $61, $10, $36, $3e, $9b, $3e, $f7, $87, $3c, $91, $3a, $91, $39, $91, $3a, $91, $3c
	.db $91, $3e, $91, $3c, $91, $39, $81, $8f, $37, $b1, $61, $0f, $37, $3e, $99, $3e, $f7, $cd, $61, $f2, $3e, $34, $95, $8f
	.db $61, $12, $39, $41, $9b, $41, $f7, $87, $3f, $91, $3a, $91, $37, $91, $3a, $91, $3f, $91, $41, $91, $3f, $91, $3a, $81
	.db $8f, $3e, $a1, $61, $f0, $3e, $33, $a1, $61, $f0, $3d, $3b, $85, $32, $99, $61, $0e, $32, $3f, $b1, $3f, $a9, $61, $f1
	.db $3f, $36, $a1, $36, $99, $61, $11, $36, $43, $a1, $8f, $43, $f7, $bf, $f9, $f3, $fd
	.dw .song0ch8loop
